import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header/Header";
import Footer from "@/components/layout/Footer/Footer";
import ScrollTopButton from "@/components/ui/ScrollTopButton/ScrollTopButton";
import MusicPlayer from "@/components/layout/MusicPlayer/MusicPlayer";
import Providers from "./providers";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin", "cyrillic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${montserrat.className} ${montserrat.variable}`}>
        <Providers>
          <Header />
          {children}
          <MusicPlayer />
          <ScrollTopButton />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
